# Generated by Django 3.1.4 on 2020-12-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('contacts', models.CharField(max_length=100)),
                ('image', models.ImageField(max_length=120, upload_to='')),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_pub'],
            },
        ),
    ]
